source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for OC
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'MJRefresh','3.2.2'
  pod 'OpenSSL',:path => './LocalSpec/OpenSSL'
  pod 'CocoaLumberjack','3.6.0'
  pod 'fishhook'
  pod 'Bugly'
  pod 'SAMKeychain'
  pod 'ReactiveObjC'
  pod 'JLRoutes'
  pod 'YYModel'
  pod 'YYCategories'
  pod 'YYText'
  pod 'CKYPhotoBrowser'
  pod 'YYImage'
  
  pod 'AMapLocation', '2.6.0'
  pod 'AMapSearch', '6.1.1'

end

target 'OCTests' do
  pod 'OCMock'
end
