# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for OC
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'MJRefresh','3.2.2'
  pod 'OpenSSL',:path => './LocalSpec/OpenSSL'
  pod 'CocoaLumberjack','3.6.0'
  pod 'fishhook', :git => 'https://github.com/facebook/fishhook.git'
  pod 'Bugly'
  pod 'SAMKeychain'
  pod 'ReactiveObjC'
  pod 'JLRoutes'
  pod 'YYModel'
  pod 'YYCategories'
  pod 'YYText'
  pod 'CKYPhotoBrowser'
  pod 'YYImage'
  
  pod 'AMapLocation', '2.6.0'
  pod 'AMapSearch', '6.1.1'
  
  #直播推流，源地址：https://github.com/LaiFengiOS/LFLiveKit
  pod 'LFLiveKit', :git => 'https://gitee.com/yier123456/LFLiveKit.git’, :tag => ‘2.6'
  
  #直播拉流用的IJK,这人放gitee上cocoapods怎么验证过的，自己试了，cdn提示访问不了gitee：
  pod 'IJKMediaFramework', :git => 'https://gitee.com/renzifeng/IJKMediaFramework.git’, :tag => ‘0.1.5'
  
  #可以换成audioKit
  pod 'TheAmazingAudioEngine'
  
  #唱吧的HTTP缓存策略
  pod 'KTVHTTPCache', '~> 2.0.0'
  
end

target 'OCTests' do
  pod 'OCMock'
end
